import { DayOfWeek, PoolType } from './lazdynu-baseinas.type';

export const TIMETABLE_DATA: {
  [key in PoolType]: { [key in DayOfWeek]: { [key: string]: { [key: string]: string } } };
} = {
  [PoolType.HALF]: {
    [DayOfWeek.MONDAY]: {
      '06:00-06:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '06:45-07:30': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '07:30-08:15': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '08:15-09:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:00-09:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:45-10:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '10:30-11:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '11:15-12:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:00-12:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:45-13:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '13:30-14:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '14:15-15:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:00-15:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:45-16:30': {
        '1': 'club_diving',
        '2': 'club_diving',
        '3': 'club_diving',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '16:30-17:15': {
        '1': 'rental',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'club',
      },
      '17:15-18:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'club',
      },
      '18:00-19:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'club',
      },
      '19:00-19:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'club_waterpolo',
        '6': 'public',
        '7': 'public',
        '8': 'disabled',
      },
      '19:45-20:30': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '20:30-21:15': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '21:15-22:00': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
    },
    [DayOfWeek.TUESDAY]: {
      '06:00-06:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '06:45-07:30': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '07:30-08:15': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '08:15-09:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:00-09:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:45-10:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '10:30-11:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '11:15-12:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:00-12:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:45-13:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '13:30-14:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '14:15-15:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:00-15:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:45-16:30': {
        '1': 'club_diving',
        '2': 'club_diving',
        '3': 'club_diving',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'club',
      },
      '16:30-17:15': {
        '1': 'rental',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'club',
        '7': 'club',
        '8': 'club',
      },
      '17:15-18:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'club',
        '7': 'club',
        '8': 'club',
      },
      '18:00-19:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'pentathlon',
        '6': 'public',
        '7': 'public',
        '8': 'club_waterpolo',
      },
      '19:00-19:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'club_waterpolo',
        '8': 'club_waterpolo',
      },
      '19:45-20:30': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '20:30-21:15': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '21:15-22:00': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
    },
    [DayOfWeek.WEDNESDAY]: {
      '06:00-06:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '06:45-07:30': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '07:30-08:15': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '08:15-09:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:00-09:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:45-10:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '10:30-11:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '11:15-12:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:00-12:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:45-13:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '13:30-14:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '14:15-15:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:00-15:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:45-16:30': {
        '1': 'club_diving',
        '2': 'club_diving',
        '3': 'club_diving',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '16:30-17:15': {
        '1': 'rental',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'club',
      },
      '17:15-18:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'club',
        '8': 'club',
      },
      '18:00-19:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'disabled',
      },
      '19:00-19:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'club_waterpolo',
        '6': 'public',
        '7': 'public',
        '8': 'disabled',
      },
      '19:45-20:30': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '20:30-21:15': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '21:15-22:00': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
    },
    [DayOfWeek.THURSDAY]: {
      '06:00-06:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '06:45-07:30': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '07:30-08:15': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '08:15-09:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:00-09:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:45-10:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '10:30-11:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '11:15-12:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:00-12:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:45-13:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '13:30-14:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '14:15-15:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:00-15:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:45-16:30': {
        '1': 'club_diving',
        '2': 'club_diving',
        '3': 'club_diving',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'club',
      },
      '16:30-17:15': {
        '1': 'rental',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'club',
        '7': 'club',
        '8': 'club',
      },
      '17:15-18:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'club',
        '7': 'club',
        '8': 'club',
      },
      '18:00-19:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'pentathlon',
        '6': 'public',
        '7': 'public',
        '8': 'club_waterpolo',
      },
      '19:00-19:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'club_waterpolo',
        '8': 'club_waterpolo',
      },
      '19:45-20:30': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '20:30-21:15': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '21:15-22:00': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
    },
    [DayOfWeek.FRIDAY]: {
      '06:00-06:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '06:45-07:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '07:30-08:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '08:15-09:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:00-09:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:45-10:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '10:30-11:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '11:15-12:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:00-12:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:45-13:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '13:30-14:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '14:15-15:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:00-15:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'club',
        '8': 'public',
      },
      '15:45-16:30': {
        '1': 'club_diving',
        '2': 'club_diving',
        '3': 'club_diving',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'trainer',
        '8': 'public',
      },
      '16:30-17:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'club',
        '8': 'club',
      },
      '17:15-18:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'club',
        '8': 'club',
      },
      '18:00-19:00': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'disabled',
      },
      '19:00-19:45': {
        '1': 'diving',
        '2': 'diving',
        '3': 'diving',
        '4': 'diving',
        '5': 'club_waterpolo',
        '6': 'public',
        '7': 'public',
        '8': 'disabled',
      },
      '19:45-20:30': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '20:30-21:15': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '21:15-22:00': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
    },
    [DayOfWeek.SATURDAY]: {
      '06:00-06:45': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '06:45-07:30': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '07:30-08:15': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '08:15-09:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:00-09:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'club',
        '8': 'public',
      },
      '09:45-10:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'club',
        '8': 'public',
      },
      '10:30-11:15': {
        '1': 'club_diving',
        '2': 'club_diving',
        '3': 'club_diving',
        '4': 'club_diving',
        '5': 'club_diving',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '11:15-12:00': {
        '1': 'club_diving',
        '2': 'club_diving',
        '3': 'club_diving',
        '4': 'club_diving',
        '5': 'club_diving',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:00-12:45': {
        '1': 'club_waterpolo',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:45-13:30': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '13:30-14:15': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '14:15-15:00': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'club_waterpolo',
        '6': 'club_waterpolo',
        '7': 'public',
        '8': 'public',
      },
      '15:00-15:45': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:45-16:30': {
        '1': 'club_waterpolo',
        '2': 'club_waterpolo',
        '3': 'club_waterpolo',
        '4': 'club_waterpolo',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '16:30-17:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '17:15-18:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '18:00-19:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '19:00-19:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '19:45-20:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '20:30-21:15': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '21:15-22:00': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
    },
    [DayOfWeek.SUNDAY]: {
      '06:00-06:45': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '06:45-07:30': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '07:30-08:15': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '08:15-09:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:00-09:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '09:45-10:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '10:30-11:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '11:15-12:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:00-12:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '12:45-13:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '13:30-14:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '14:15-15:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:00-15:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '15:45-16:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '16:30-17:15': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '17:15-18:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '18:00-19:00': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '19:00-19:45': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '19:45-20:30': {
        '1': 'public',
        '2': 'public',
        '3': 'public',
        '4': 'public',
        '5': 'public',
        '6': 'public',
        '7': 'public',
        '8': 'public',
      },
      '20:30-21:15': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
      '21:15-22:00': {
        '1': 'closed',
        '2': 'closed',
        '3': 'closed',
        '4': 'closed',
        '5': 'closed',
        '6': 'closed',
        '7': 'closed',
        '8': 'closed',
      },
    },
  },
};
